# api/config/packages/api_platform.yaml
api_platform:
    # The title of the API.
    title: 'Gift API'

    # The description of the API.
    description: 'Gift API Description'

    # The version of the API.
    version: '0.0.1'

    defaults:
        format: jsonld
        pagination_items_per_page: 10
        pagination_client_items_per_page: true
        pagination_maximum_items_per_page: 25

    mapping:
        paths: [ '%kernel.project_dir%/src/Entity', '%kernel.project_dir%/src/ApiResource' ]

    formats:
        jsonld: ['application/ld+json']
#        jsonhal: ['application/hal+json']
#        jsonapi: ['application/vnd.api+json']
#        json: ['application/json']
#        yaml: ['application/x-yaml']
#        csv: ['text/csv']
#        html: ['text/html']

#    not sure how that's used. Leaving it here for reference
#    error_formats:
#        jsonproblem: [ 'application/problem+json' ]
#        jsonld: [ 'application/ld+json' ] # Hydra error formats
#        jsonapi: [ 'application/vnd.api+json' ]

    # Set this to false if you want Webby to disappear.
    show_webby: true

    # Specify a name converter to use.
    name_converter: ~

    # Specify an asset package name to use.
    asset_package: null

    # Specify a path name generator to use.
    path_segment_name_generator: 'api_platform.path_segment_name_generator.dash'

    validator:
        # Enable the serialization of payload fields when a validation error is thrown.
        # If you want to serialize only some payload fields, define them like this: [ severity, anotherPayloadField ]
        serialize_payload_fields: []

        # To enable or disable query parameters validation on collection GET requests
        query_parameter_validation: true

    eager_loading:
        # To enable or disable eager loading.
        enabled: true

        # Fetch only partial data according to serialization groups.
        # If enabled, Doctrine ORM entities will not work as expected if any of the other fields are used.
        fetch_partial: false

        # Max number of joined relations before EagerLoading throws a RuntimeException.
        max_joins: 30

        # Force join on every relation.
        # If disabled, it will only join relations having the EAGER fetch mode.
        force_eager: true

    # Enable the Swagger documentation and export.
    enable_swagger: true

    # Enable Swagger UI.
    enable_swagger_ui: true

    # Enable ReDoc.
    enable_re_doc: true

    # Enable the entrypoint.
    enable_entrypoint: true

    # Enable the docs.
    enable_docs: true

    # Enable the data collector and the WebProfilerBundle integration.
    enable_profiler: true

    collection:
#        # The name of the query parameter to filter nullable results (with the ExistsFilter).
#        exists_parameter_name: 'exists'
#
#        # The default order of results.
#        order: 'ASC'
#
#        # The name of the query parameter to order results (with the OrderFilter).
#        order_parameter_name: 'order'
#
#        pagination:
#            enabled: true               # Enable pagination globally
#            enabled_parameter_name: 'pagination'  # Query parameter to enable/disable pagination
#            items_per_page_parameter_name: 'itemsPerPage'  # Query parameter to set items per page
#            page_parameter_name: 'page'          # Query parameter for the page number
#            partial_parameter_name: 'partial'    # Query parameter for partial collection requests
#
#        mapping:
#            # The list of paths with files or directories where the bundle will look for additional resource files.
#            paths: []
#
#        # The list of your resources class directories. Defaults to the directories of the mapping paths but might differ.
#        resource_class_directories:
#            - '%kernel.project_dir%/src/Entity'
#
#        doctrine:
#            # To enable or disable Doctrine ORM support.
#            enabled: true
#
#        doctrine_mongodb_odm:
#            # To enable or disable Doctrine MongoDB ODM support.
#            enabled: false

#        oauth:
#            # To enable or disable OAuth.
#            enabled: false
#
#            # The OAuth client ID.
#            clientId: ''
#
#            # The OAuth client secret.
#            clientSecret: ''
#
#            # The OAuth type.
#            type: 'oauth2'
#
#            # The OAuth flow grant type.
#            flow: 'application'
#
#            # The OAuth token URL. Make sure to check the specification tokenUrl is not needed for an implicit flow.
#            tokenUrl: ''
#
#            # The OAuth authentication URL.
#            authorizationUrl: ''
#
#            # The OAuth scopes.
#            scopes: []
#
#        graphql:
#            # Enabled by default with installed api-platform/graphql.
#            enabled: false
#
#            # The default IDE (graphiql or graphql-playground) used when going to the GraphQL endpoint. False to disable.
#            default_ide: 'graphiql'
#
#            graphiql:
#                # Enabled by default with installed api-platform/graphql and Twig.
#                enabled: false
#
#            graphql_playground:
#                # Enabled by default with installed api-platform/graphql and Twig.
#                enabled: false
#
#            introspection:
#                # Enabled by default with installed api-platform/graphql.
#                enabled: true
#
#            # The nesting separator used in the filter names.
#            nesting_separator: _
#
#            collection:
#                pagination:
#                    enabled: true
#
#        swagger:
#            # The active versions of OpenAPI to be exported or used in the swagger_ui. The first value is the default.
#            versions: [2, 3]
#
#            # The swagger API keys.
#            api_keys: []
#              # The name of the header or query parameter containing the API key.
#              # name: ''
#
#              # Whether the API key should be a query parameter or a header.
#            # type: 'query' or 'header'
#
#            swagger_ui_extra_configuration:
#                # Controls the default expansion setting for the operations and tags. It can be 'list' (expands only the tags), 'full' (expands the tags and operations) or 'none' (expands nothing).
#                docExpansion: list
#                # If set, enables filtering. The top bar will show an edit box that you can use to filter the tagged operations that are shown.
#                filter: false
#                # You can use any other configuration parameters too.
#
#        openapi:
#            # The contact information for the exposed API.
#            contact:
#                # The identifying name of the contact person/organization.
#                name:
#                # The URL pointing to the contact information. MUST be in the format of a URL.
#                url:
#                # The email address of the contact person/organization. MUST be in the format of an email address.
#                email:
#            # A URL to the Terms of Service for the API. MUST be in the format of a URL.
#            termsOfService:
#            # The license information for the exposed API.
#            license:
#                # The license name used for the API.
#                name:
#                # URL to the license used for the API. MUST be in the format of a URL.
#                url:
#
#        http_cache:
#            # To make all responses public by default.
#            public: ~
#
#            invalidation:
#                # To enable the tags-based cache invalidation system.
#                enabled: false
#
#                # URLs of the Varnish servers to purge using cache tags when a resource is updated.
#                varnish_urls: []
#
#                # To pass options to the client charged with the request.
#                request_options: []
#
#                # Use another service as the purger for example "api_platform.http_cache.purger.varnish.xkey"
#                purger: 'api_platform.http_cache.purger.varnish.ban'
#
#        mercure:
#            # Enabled by default with installed symfony/mercure-bundle.
#            enabled: false
#
#            # The URL sent in the Link HTTP header. If not set, will default to MercureBundle's default hub URL.
#            hub_url: null
#
#        messenger:
#            # Enabled by default with installed symfony/messenger and not installed symfony/symfony.
#            enabled: false
#
#        elasticsearch:
#            # To enable or disable Elasticsearch support.
#            enabled: false
#
#            # The hosts to the Elasticsearch nodes.
#            hosts: []
#
#            # The mapping between resource classes and indexes.
#            mapping: []
#
#        # The list of exceptions mapped to their HTTP status code.
    exception_to_status:
        # With a status code.
        App\Security\Exception\ApiAccessDeniedException: 403
        App\Security\Exception\ApiMultipleUserAccountsException: 403
        App\Security\Exception\ApiNoUserAccountException: 403
        App\Security\Exception\ApiTokenExpiredException: 401
        App\Security\Exception\ApiTokenValidationException: 401

            # Or with a constant defined in the 'Symfony\Component\HttpFoundation\Response' class.
#            ApiPlatform\Exception\InvalidArgumentException: !php/const Symfony\Component\HttpFoundation\Response::HTTP_BAD_REQUEST
#
#            ApiPlatform\Exception\FilterValidationException: 400
#
#            Doctrine\ORM\OptimisticLockException: 409
#
#            # ...
#
#        # The list of enabled formats. The first one will be the default.
#        formats:
#            jsonld:
#                mime_types: ['application/ld+json']
#
#            json:
#                mime_types: ['application/json']
#
#            html:
#                mime_types: ['text/html']
#
#            # ...
#
#        # The list of enabled patch formats. The first one will be the default.
#        patch_formats: []
#
#        # The list of enabled error formats. The first one will be the default.
#        error_formats:
#            jsonproblem:
#                mime_types: ['application/problem+json']
#
#            jsonld:
#                mime_types: ['application/ld+json']
#
#            # ...
#
#        # Global resources defaults, see in the next section.
#        defaults:
#        # ...