# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    env(CACHE_AUTH_TOKENS): "false"
    env(AUTH_USE_HTTP): "false"
    env(LOG_LEVEL): "error"

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            $appEnv: '%env(APP_ENV)%'

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Serializer/GiftListItemCommentNormalizer.php'

    App\Controller\:
        resource: '../src/Controller/'
        tags: [ 'controller.service_arguments' ]

    App\OpenApi\OpenApiDecorator:
        decorates: 'api_platform.openapi.factory'
        tags: [ 'api_platform.openapi.factory' ]

    App\ApiPlatform\Filter\MultiFieldSearchFilter:
        arguments:
            $resourceMetadataFactory: '@api_platform.metadata.resource.metadata_collection_factory'
        tags: [ 'api_platform.filter' ]

    App\ApiPlatform\Filter\DeviceOwnershipFilter:
        tags: [ 'api_platform.filter' ]

    App\ApiPlatform\Filter\RelationAliasFilter:
        tags: [ 'api_platform.filter' ]

    App\DataProvider\UserDataProvider:
        arguments:
            $managerRegistry: '@doctrine'
            $collectionExtensions: !tagged_iterator api_platform.doctrine.orm.query_extension.collection
        tags: [ 'api_platform.state_provider' ]

    bit_as_bool_type:
        class: App\Doctrine\BitAsBoolType

    App\EventListener\IdGeneratorListener:
        tags:
            - { name: doctrine.event_listener, event: prePersist, priority: 1 }

    App\EventListener\GiftListItemReservationListener:
        tags:
            - { name: doctrine.event_listener, event: prePersist, priority: 0 }

    App\EventSubscriber\RemoveGroupOverrideSubscriber:
        tags:
            - { name: kernel.event_subscriber }

    App\EventSubscriber\AdminGroupSecuritySubscriber:
        tags:
            - { name: kernel.event_subscriber }

    App\EventSubscriber\ApiResponseSubscriber:
        tags:
            - { name: kernel.event_subscriber }

    App\Serializer\CustomSerializerContextBuilder:
        decorates: 'api_platform.serializer.context_builder'
        arguments: [ '@App\Serializer\CustomSerializerContextBuilder.inner' ]

    App\Controller\User\CreateController:
        autowire: true
        autoconfigure: true
        public: true

    App\Controller\User\UpdateController:
        autowire: true
        autoconfigure: true
        public: true

    App\Serializer\CustomViolationListNormalizer:
        tags:
            - { name: serializer.normalizer, priority: 300 }

#    App\Security\Voter\Voter:
#        abstract: true
#        arguments:
#            $logger: '@monolog.logger.security'
#
#    # Define your concrete voter, extending the abstract one, and tag it properly.
#    App\Security\Voter\UserOrganizationVoter:
#        parent: App\Security\Voter\Voter
#        tags:
#            - { name: security.voter }


    App\Repository\Wrapper\PDOWrapper:
        arguments:
            $dsn: 'pgsql:host=%env(DB_HOST)%;port=%env(DB_PORT)%;dbname=%env(DB_NAME)%;user=%env(DB_USERNAME)%;password=%env(DB_PASSWORD)%'

#    App\Security\Factory\TokenDataRepositoryFactory: ~
#    App\Repository\Interface\TokenDataRepositoryInterface:
#        factory: [ 'App\Security\Factory\TokenDataRepositoryFactory', 'getRepository' ]
#        arguments:
#            $useCache: '%env(bool:CACHE_AUTH_TOKENS)%'
#            $cache: '@auth_tokens.cache'
#            $authDomain: '%env(AUTH_API_DOMAIN)%'
#            $authTokenValidationEndpoint: '%env(AUTH_TOKEN_VALIDATION_ENDPOINT)%'
#            $authMiddlewareToken: '%env(AUTH_MIDDLEWARE_TOKEN)%'
#            $useHttp: '%env(bool:AUTH_USE_HTTP)%'
#            $db: '@App\Repository\Wrapper\PDOWrapper'
#
#    App\Repository\TokenDataRepositoryCache:
#        arguments:
#            $cache: '@auth_tokens.cache'
#            $authDomain: '%env(AUTH_API_DOMAIN)%'
#            $authTokenValidationEndpoint: '%env(AUTH_TOKEN_VALIDATION_ENDPOINT)%'
#            $authMiddlewareToken: '%env(AUTH_MIDDLEWARE_TOKEN)%'
#            $useHttp: '%env(bool:AUTH_USE_HTTP)%'
#
#    App\Repository\TokenDataRepositoryApi:
#        arguments:
#            $authDomain: '%env(AUTH_API_DOMAIN)%'
#            $authTokenValidationEndpoint: '%env(AUTH_TOKEN_VALIDATION_ENDPOINT)%'
#            $authMiddlewareToken: '%env(AUTH_MIDDLEWARE_TOKEN )%'
#            $useHttp: '%env(bool:AUTH_USE_HTTP)%'

    App\Logging\Debug:
        calls:
            - method: setLogger
              arguments: [ '@logger' ]

    App\Serializer\RelationIdentifierAppenderNormalizer:
        decorates: 'api_platform.jsonld.normalizer.item'
        arguments:
            $decoratedNormalizer: '@App\Serializer\RelationIdentifierAppenderNormalizer.inner'
        tags: [ 'serializer.normalizer' ]

    App\Serializer\GiftListItemCommentNormalizer:
        tags:
            - { name: 'serializer.normalizer', priority: 64 }

    App\Serializer\OneToManyCountsNormalizer:
        tags:
            - { name: 'serializer.normalizer', priority: 200 }

    App\Serializer\EntityIdToIriDenormalizer:
        tags:
            - { name: serializer.normalizer, priority: -885 }

    App\Serializer\RelationAliasDenormalizer:
        tags:
            - { name: serializer.normalizer, priority: -880 }